### ISSUE TITLE
api is out of date

### ISSUE THREAD

**Issue by ghost** [authenticname/fortnite-checker#2]
the api link does not exist anymore, the owner has temporarily shut it down

**Comment by ghost** [comment]
PS C:\Users\\Downloads\fortnite-checker-master> npm start

> fortnite_bulk_username_checker@1.0.0 start C:\Users\\Downloads\fortnite-checker-master
> node src/index

**Comment by alexthemaster** [comment]
Noted, will mention it in the README file.
Thanks for letting us know!
